name: CI

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-rust:
    name: Rust Project
    runs-on: ubuntu-latest
    steps:
      - name: Run ls
        run: | 
          ls
      - name: Run unit tests
        run: |
          echo ${{ github.ref }}
