name: Release

on:
  push:
    tags:
      - 'v*'


jobs:
  ci:
    uses: zsluedem/zsluedem/.github/workflows/ci.yml@main
  ci-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ci.yml@main
  unit-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -al
