name: Release

on:
  push:
    tags:
      - 'v*'


jobs:
  unit-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: [build-rust]
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -al
