name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  ci:
    uses: zsluedem/zsluedem/.github/workflows/ci.yml@main
  ci-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          echo ${{ matrix.target }} > target-${{ matrix.target }}.txt
          echo "\n" >> target-${{ matrix.target }}.txt
          echo ${{ github.ref }} >> target-${{ matrix.target }}.txt
          echo "\n" >> target-${{ matrix.target }}.txt
          echo ${{ github.sha }} >> target-${{ matrix.target }}.txt
          echo "\n" >> target-${{ matrix.target }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: zsluedem-${{ github.sha }}
          path: target-${{ matrix.target }}.txt
  unit-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -al
      - uses: actions/download-artifact@v3
        with:
          name: zsluedem-${{ github.sha }}
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
