name: Release

on:
  push:
    tags:
      - 'v*'


jobs:
  unit-tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ci.yml@main
